#!/bin/bash
################################################################################
# <START METADATA>
# @project_name: quickbox_pro_v3
# @file_name: qbpro_v3
# @description: Downloads installation script.
# @version: 1.0.13
#
# @save_tasks:
#  automated_versioning: true
#
# @author: Jamie Dobbs (mschf)
# @author_contact: jamie.dobbs@mschf.dev
#
# @license: BSD-3 Clause (Included in LICENSE)
# Copyright (C) 2019-2022, QuickBox.IO
# All rights reserved.
# <END METADATA>
# shellcheck disable=SC2068
################################################################################

################################################################################
# @name: setup::download
# @description: setup the environment and download quickboxv3
#
# @args:
#  $@ quickbox install arguments
################################################################################
setup::download() {
  [[ $(whoami) != "root" ]] && { printf -- "%s\n" "ERROR: Install as root or via sudo." && exit 1; }
  cd "${HOME}" || { printf -- "%s\n" "Error: Unable to move to ${HOME}" && exit 1; }
  rm -f /root/quickbox_install
  DEBIAN_FRONTEND=noninteractive apt-get -yqq -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" update >/dev/null 2>&1
  apt-get -y install wget --allow-unauthenticated >/dev/null 2>&1 |
  wget -q https://lab.quickbox.io/QuickBox/pro-v3/raw/main/quickbox_install && chmod +x quickbox_install
  [[ -f /root/quickbox_install ]] && /root/quickbox_install $@ && exit 0
  exit 1
}

setup::download $@