#!/bin/bash
declare -g title text
title="An update is available!"
text="## 3.1.1.4025 (2024-03-08)

### enhancements (1 change)

- enh(qb manage db): implement fallback function to sqlite db in the event mysql swap fails"
