#!/bin/bash
declare -g title text
title="An update is available!"
text="## 3.0.0.2851 (2022-08-26)

### fixes (5 changes)

- fix(cli lang): correction to overseerr completion message if installed for subdomain
- fix(admin user edit): remove unnecessary php service reload on user edit
- fix(admin user edit): correction to header redirect on user setting updates
- fix(user): corrections to user processing on promote/demote to/from admin
- fix(overseerr): correction to database values for translation"
