#!/bin/bash
declare -g title text
title="An update is available!"
text="## 3.0.0.3073 (2022-10-05)

### enhancements (1 change)

- enh(qb -h): add additional manage functions to help manual

### fixes (1 change)

- fix(prowlarr): update build to default to updated nightly branch provided"
