#!/bin/bash
################################################################################
# <START METADATA>
# @project_name: quickbox_pro_v3
# @file_name: install
# @description: Downloads installation script.
# @version: 1.0.9
#
# @save_tasks:
#  automated_versioning: true
#
# @author: Jamie Dobbs (Mschf)
# @author_contact: jamie.dobbs@mschf.dev
#
# @license: BSD-3 Clause (Included in LICENSE)
# Copyright (C) 2019-2021, QuickBox | Jamie Dobbs
# All rights reserved.
# <END METADATA>
# shellcheck disable=SC2068
################################################################################

################################################################################
# @name: setup::download
# @description: checks the environment before continuing
#
# @args:
#  $@ quickbox install arguments
################################################################################
setup::download() {
  [[ $(whoami) != "root" ]] && { printf -- "%s\n" "ERROR: Install as root or via sudo." && exit 1; }
  cd "${HOME}" || { printf -- "%s\n" "Error: Unable to move to ${HOME}" && exit 1; }
  rm -f /root/quickbox_install
  wget -q https://lab.quickbox.io/QuickBox/pro-v3/raw/main/quickbox_install && chmod +x quickbox_install
  [[ -f /root/quickbox_install ]] && /root/quickbox_install $@ && exit 0
  exit 1
}

setup::download $@